### ISSUE TITLE
yarn test 报错

### ISSUE THREAD

**Issue by magicstf** [antfu/vueuse#103]
FAIL  packages/core/useTimeout/index.test.ts
  ● export

    [vue-composition-api] must call Vue.use(plugin) before using any function.

      2 |
      3 | export function useTimeout(interval = 1000, startRightNow = true) {
    > 4 |   const ready = ref(false)
        |                 ^
      5 |
      6 |   let timer: any = null

 PASS  packages/core/useCounter/index.test.ts
 FAIL  packages/core/useWindowSize/index.test.ts
  ● useWindowSize › should work

    expect(received).toBe(expected) // Object.is equality

    Expected: 1024
    Received: undefined

      17 |     })
      18 |
    > 19 |     expect(wrapper.vm.width).toBe(window.innerWidth)
         |                              ^
      20 |     expect(wrapper.vm.height).toBe(window.innerHeight)
      21 |   })

 ● useWindowSize › sets handler for window "resize" event

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "resize", Anything, undefined

    Number of calls: 0

      29 |     })
      30 |
    > 31 |     expect(windowAddEventListener).toHaveBeenCalledWith('resize', expect.anything(), undefined)
         |                                    ^
      32 |   })
      33 | })

**Comment by antfu** [comment]
Yeah, it's currently broken since I switch to vue-demi. I didn't get time to have a deep look about it, this article may help I guess: https://dev.to/pikax/how-to-test-your-library-for-vue-2-and-vue-next-42ao

**Comment by antfu** [comment]
Fixed, thanks
