### ISSUE TITLE
Support ServerSentEvents: useEventSource

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [antfu/vueuse#110]
**Suggested Feature**

Support **`ServerSentEvents`** via `useEventSource` the same way we have **`WebSockets`** via `useWebSocket`

here: https://github.com/antfu/vueuse/pull/111

**Comment by antfu** [comment]
I didn't know this API before, might need to learn a bit about it. It would be great if you can file a PR of it. Thanks :)

**Comment by CharlesOkwuagwu** [comment]
I'm looking at my current use-cases and trying to see how best to structure **`useSSE`**.

Currently I put all my `SSE` code for a page in one function and call it from `created()` like below boilerplate:

```
function sse() {
      try {
        let es = new EventSource('some-url')

        es.onopen = () => {
          this.connected = true
          // this connected state automatically toggles once connection is re-connected
          // console.log('sse-open')
        }

        es.onerror = () => {
          this.connected = false
          // console.log('sse-error')
        }

        // fire for every message received, if no dedicated handlers are provided
        es.onmessage = (x) => {
          // console.log('sse-msg', JSON.parse(x.data)))
        }

        es.addEventListener('action-A', (x) => {
          console.log('action-A', JSON.parse(x.data))
        })
        es.addEventListener('action-B', (x) => {
          console.log('action-B', JSON.parse(x.data))
        })
      } catch (error) {
        // console.log('SSE Error:', error)
      }
```

I don't yet have a suitable API for **`useSSE`** yet, particularly allowing for any number of callback handlers to be defined, or default to a capturing all data like **`useWebSocket`**
