### ISSUE TITLE
Adding addons with @vueuse/core dependency

### ISSUE THREAD

**Issue by regenrek** [antfu/vueuse#114]
Hi!

What's actually the recommend way to add composables from @vueuse/core to a @vueuse addon? 

If I'm going to add for example an addon `@vueuse/myaddon` and using `useLocalStorage` from `@vueuse/core`
I see two options:

*Option 1 - relative:*
Via '../../composables/useLocalStorage' the `useLocalStorage`. Here the functions gets bundled in `@vueuse/aws` too
which is not necessarily wanted.

*Option 2 - via package*
'from @vueuse/core' which requires to add `@vueuse/core` to `@vueuse/core` as dependency including updating `packages.json`. 

I would prefer first option 1 without bundling the function twice. Any ideas?

**Comment by antfu** [comment]
I would suggest going with Option 2 but with `peerDependencies`. For option 1 it will potentially bundle the function twice which affect the load size on userland.
