### ISSUE TITLE
i18n warning

### ISSUE THREAD

**Issue by axe-me** [antfu/vueuse#121]
got the warning when using the i18n package.  
```bash

 warning  in ./node_modules/@vueuse/i18n/index.esm.js

"export 'default' (imported as 'Vue') was not found in 'vue'
```

the project freshly created with vue-cli with typescript and vue3 option.

**Comment by antfu** [comment]
Thanks for catching this up. I am discussing with the author of vue-i18n to find a proper solution for this package. Will keep this tread up to date.

**Comment by antfu** [comment]
`@vueuse/i18n` was provided as a workaround before `vue-i18n` settling down the composable APIs. It's misaligned with `vue-i18n@9` and it's better not to use it. I will mark the package deprecated soon. 

If you need the composable style of `vue-i18n`:

- Vue 3: use [`vue-i18n@next`](https://github.com/intlify/vue-i18n-next) directly
- Vue 2: use [`vue-i18n-composable`](https://github.com/intlify/vue-i18n-composable)
