### ISSUE TITLE
useStorage

### ISSUE THREAD

**Issue by magicstf** [antfu/vueuse#122]
let rawValue = storage.getItem(key)
      if (rawValue === undefined && defaultValue) {
        rawValue = Serializers[type].write(defaultValue)
        storage.setItem(key, rawValue)
      } else {
        data.value = Serializers[type].read(rawValue, defaultValue)
      }

localStorage.setItem方法必须穿俩个参数，不会出现有key，值是undefined的情况吧？这个判断的意义是？

**Comment by antfu** [comment]
Sorry, I don't get your point. Which line do you mean?
