### ISSUE TITLE
Issue with createGlobalState

### ISSUE THREAD

**Issue by Demivan** [antfu/vueuse#130]
`createGlobalState` stops tracking changes after component that first used global state is disposed.

Tried it with `vue@3` and can reproduce it there too, so it is not  `@vue/composition-api` issue.

Added pull request with reproduction tests: #129

**Comment by antfu** [comment]
This is a limitation of current Vue's API design: https://github.com/vuejs/vue-next/issues/1532

I am already working on an RFC to addressing this: https://github.com/vuejs/rfcs/pull/212

Thanks

**Comment by Demivan** [comment]
Thanks for info. Will monitor RFC then.
Maybe this caveat should be added to `vueuse` docs for now?

**Comment by Demivan** [comment]
Inspired by `effectScope` I have fixed #129 by creating new Vue component to hold reactive scope. Seems to work fine with Vue 2 and 3

**Comment by antfu** [comment]
I think that will do for now, thanks!

**Comment by antfu** [comment]
Released in 4.0.0-beta.16.
