### ISSUE TITLE
RFC: possible useRefHistory API improvements

### ISSUE THREAD

**Issue by matias-capeletto** [antfu/vueuse#137]
Hey @antfu! Thanks for all the work with the lib ❤️ 

Great to see you added a composable for ref history! We [had to build one](https://github.com/Leniolabs/layoutit-grid/blob/main/src/composables/useRefHistory.js) because the `useUndo` from vue-composable was not flexible enough for our use case. I was planning to submit a proposal for a similar one at one point. The API is not the same though, so I may release it as a separate lib since it has different tradeoffs. There are some API tweaks that could be useful in the current on in vueuse. If you like any of these changes, I could create PRs for them.

1. Add option to avoid `flush: 'sync'`
I think the default should be for it not to be 'sync'. We had several actions that were generating spurious history points because of this. An example could be to in a handler to change a size that is defined as {value,unit}, and you need to touch both. We could do this using pause/resume but it will be quite error prone in some apps.
2. Rename `history, redoHistory` to `prev, next`
This is the way it is in vue-composable `useUndo`. I think they are more in line with the rest of the API (undo, redo, clear) and it reads better when you use an object for the composable return:
```
const history = useRefHistory(aRef)
if( history.prev.length > 0 ) { ... } // instead of history.history
if( history.next.length > 0 ) { ... } // instead of history.redoHistory
```
3. Expose `batch(), commit()` functions, that complements `pause(), resume()` (it can be discussed if we should have both pairs after adding batch and commit, IMO they both have different use cases)
When doing real time changes, like dragging or playing with a slider, we want only one history point for the whole interaction. The code for this would be
```
history.batch()
// change state, across several user events (pointermove for example)
```
and when the interaction ends
```
history.commit()
```
If we want to do the same with `pause(), resume()`, we would need to add another set to the ref to trigger the history point after it is resumed. 
I also think that `batch(), commit()` is better suited for this cases because we can add a `cancel()` function, that will go back to the last history point, finish the batch and resume history (it can also be called `revert()` if we want to follow a git analogy).
`commit()` can also let us build a manual history composable, with the same API, where the trigger is not automatic but the user is the one in charge of deciding when there is a history point. It also serves as a way to add a sync history point in case the user decides not to use `flush: 'sync'` but still needs it in a particular case.

I think the other differences with what I had in mind are more about extra features and configuration, and it is not clear to me that the gained flexibility will be enough to justify a more complex API in vueuse. This is why I think there could be space for another lib, with different tradeoffs (more options, but more time to learn it, and more verbose config). But the above proposals could be good for vueuse, and later if people migrate from vue-composable or to other libs, they would have a closer API.

**Comment by antfu** [comment]
I don't expect to have this detailed feedback in such a short time. Thanks a lot!

1. I would love to not using this and handle the control to users via options, but I am not sure how to make it right. The main reason is that `undo` `redo` would not work properly without `sync`. `resume()` will be called before `watch`. Do you have any solutions for this?

2. Sounds good, let's go for it! I also like the `capacity` in your implementation than `limit`, let's have it too.

3. `batch()` sounds good, but I am thinking if this would be better:
```ts
// iif
history.batch((cancel) => {
  // a batch of changes, but only one record will be commited after the function ends
})
```
What do you think?

PR welcome, thanks!

**Comment by matias-capeletto** [comment]
You are welcome!

1. Do you mean the issue of performing an undo, that triggers another watch of the ref? In our implementation, it is working without the `flush: 'sync'` because there is a guard against adding a history point with the same representation as the last one, in this line: https://github.com/Leniolabs/layoutit-grid/blob/main/src/composables/useRefHistory.js#L40
This works well because I am separating clone into two options: `serialize` and `parse`. So I can shallow compare the strings without issues. Given that we are already using JSON.stringify in most cases, I think it is good to make use of it. Another reason for separating the clone in two, was to add later support for persistence in local storage for example of the last valid history point, and auto load it on start up (kind of how excalidraw works in this regard).
I didn't expose prev and next because of this, but I think we can keep the string representation internally, and expose prev and next as computed over it. Or even better, try to avoid calling parse if the user is not going to access that history point. So you only parse when there is a get, this can make a difference when you are generating a lot of history points for a ref that holds big nested objects. Given that most user will not need to give us a custom clone, I think that it is not that much work for that few cases to give us serialize and parse (or maybe stringify and parse if we want to be more inline with the JSON API). In the case of our app, I am using these config points https://github.com/Leniolabs/layoutit-grid/blob/main/src/store.js#L245, like this:
```
const history = useRefHistory(state,{
  stringify(value) {
    return JSON.stringify({ state: value, version: 1 }, parentRemover)
  }
  parse(rep) {
    return parentify(JSON.parse(rep).state)
  }
}
```
because our state is a nested object that has back pointers to the parents and I need to remove them. You can see here that I am also including a version tag, because even if it is not supported yet, I was already thinking on persisting the state (and in case we ever change the representation format, be able to load old versions too).

2. Great! I'll prepare a PR later 👍 
About `capacity`, Iooks like it is called `maxLength` in vue-composable, but in this case, I think renaming is ok.

3. Cool! So let's go with exposing both `batch, cancel, commit` and `pause, resume`, no?
I thought about exposing the change set as a function, our problem with that approach is that we want a batch across several user interactions (like dragging the lines in https://grid.layoutit.com/). We start the batch() as soon as the pointermove is far enough, and finish it [on pointerup](https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/grid/GridCell.vue#L181) (batch and commit are called startAtomicChange and endAtomicChange in that version). So only exposing batch as a function is not enough for this use case (if you see a way let me know). But I like a lot that pattern when you have to deal with async functions, Should both options be exposed? A `batch()` without args will start an open ended batch (for pointermove like interactions) and `batch(changeSet)` would expose cancel and commit to that handler. I also think the signature should be
```
batch( (commit,cancel) => { ... } )
```
so we support a commit in a timeout, or deep in callback based async functions. Auto commit on function end would not work in these cases I think. Maybe we could autocommit when the handler is a promise, but it could be confusing (we maybe need to split the functions to avoid overloading that much)

I'll prepare a commit for 2 then while we discuss the other points 🙂

**Comment by antfu** [comment]
Thanks for the PR. But let me think a bit more about 1 & 3.

**Comment by antfu** [comment]
For 1., I think it's a good idea to expose `serialize` and `deserialize` as it adds more flexibility to different usages. However, I don't think it's good to store the state in strings. The state history is meaningful to some usages (e.g. just tracking the changes of a number, not only undo and redo but the full history trace). So in the PR, I left the `dump` and `parse` bypass by default, and you can use serialize them into strings or whatever you want (with proper typing!).

For 3., `commit` is good to have. But I don't really get what `batch` and `cancel` is trying to achieve. Can you provide an example of usage? 

Let me know what you think. Thanks.

**Comment by matias-capeletto** [comment]
1. Nice, I agree with you that it is nice to have the real values in the history. I think that even in the case you use JSON.stringify, we could expose the history as parsed objects in next, prev. Maybe there is a way to avoid the parsing until it is requested. Did you see the guard to be able to avoid the use of `flush: 'sync'`?

2. Ya, if you go to https://grid.layoutit.com/, the app support history, and if you drag one of the grid lines to change the track sizes, only one history point is generated. The pattern to achieve that is (in pseudo code):
```
function pointermove(event) {
  const point = toPoint(event)
  if( ! dragging.value && farEnough(initialPoint, point) ) {
    history.batch();
    dragging.value = { ... }
  }
  if( dragging.value ) {
    moveTo(point)
  }
}
function pointerup(event) {
  if( dragging.value ) {
    history.commit();
  }
}
function onEsc() {
  if( dragging.value ) {
    history.cancel()
  }
}
```
The production code for the real example is [here](https://github.com/Leniolabs/layoutit-grid/blob/main/src/components/grid/GridCell.vue#L148) (`batch` and `commit` are called `startAtomicChange` and `endAtomicChange` in that version).

So, we start an interaction calling `history.batch()`, we receive any number of user events (pointermove, maybe others) and update the ref normally (history points are not being generated), and when the interaction ends we call `history.commit()`, that pushes the current ref value to the history and re enables the auto commit behavior.

**Comment by antfu** [comment]
1. The guard you used works because they are strings (and you will need to call an extra serialize). I am doubting if it's a good practice. What's a problem of `sync` tho? In the description of your first comment, how about:

```ts
history.batch(() => {
  a.value = 1
  a.unit = 'cm'
})
```

2. Based on your description, can I say `batch === pause`, `commit == resume + push current state`, `cancel == undo, but not populate the next stack`?

**Comment by matias-capeletto** [comment]
1. I see now that extra serialize call... indeed, that is a deal breaker. I will need to think if there is a way to avoid it. The idea behind avoiding `sync` was to avoid having to use the history in a lot of places in the app. 

With the `batch` function, it may not be that intrusive, it could even be a functional wrapper that returns the value of the original function, so you can directly wrap setter in the same way you would use debounce, or utilities like it.

Maybe it is the right way to go for vueuse, as it is consistent and easy to explain. I think it may force people to think about bundling of history points upfront, and avoid bugs like adding a timeout or making a setter async and introduce silent bugs.

2. Yes, that it right. There is another tweak in our implementation though, because `batch` is not the same as `pause` as it increments an internal counter instead of a boolean so if you do: 
```
  batch() 
  batch() 
  change A 
  change B 
  commit() 
  change C 
  change D 
  commit()
``` 
it still generates only two history points. So commit() is not resuming in the first call, only in the second one here. I did not proposed this because I think we should have some way to properly merge concurrent batches to make this robust, so probably better to say it is not supported.

But if this is not important, `batch` could be removed, and the API could use only `commit` and `cancel`. And use it like
```
// Cross events change set
history.pause()
... changes
history.commit() // or history.cancel()
```
```
// Sync or promise based change set
history.commit( (cancel) => {
  ... changes,
})
```
It is tempting to avoid `batch`, but what I like about it is that it is easier to explain what `cancel` means... as you are cancelling the a batch of changes. If you "cancel the pause" it is easy to confuse cancel with resume. But good documentation may be enough here.

**Comment by antfu** [comment]
2. The behavior you described feels uncertain to me as it heavily relies on the internal state which is not transparent to the user. Calling `batch()` twice does not make sense to me either.

I would like those APIs to be as atomical as possible. I would propose the APIs like:

- `pause` pause the tracking (will be accessible in `history.tracking.value`)
- `resume(commit?: boolean)` resume the tracking
  - if passed `true`, will create a commit on resuming. 
- `batch` a sugar for auto-pause & auto-resume+commit within a function
- `commit` manually push a new historical record, regardless of the state, and does not do comparison checks.
  - It does not make sense to compare values that aren't primitive
- `reset` (cancel) reset ref value to the head of the history.

```ts
history.resume(true)

// equals to:
history.resume()
hisotry.commit()
```

```ts
history.batch(() => {
  a.value = 1
  a.unit = 'cm'
})

// equals to:
history.pause()
a.value = 1
a.unit = 'cm'
history.resume()
hisotry.commit()
```

```ts
history.batch((cancel) => {
  a.value = 1
  a.unit = 'cm'
  cancel()
})

// equals to:
history.pause()
a.value = 1
a.unit = 'cm'
history.resume()
hsitory.reset()
```

For more advanced/custom logics, users should be able to compose them with these APIs and make one on their own I think.

One of my goals on this is trying to make it possible for you to reuse in layoutit to prove its flexibility while avoiding bad trade-off as possible. Thanks!

**Comment by matias-capeletto** [comment]
I like it! For a change set across use events, I would use `pause()` when the interaction starts and `resume(true)` when it ends then. I assume that you would also leave async support as something that the user can built with these primitives, and not part of the API. 
Thanks again for your work, and thanks a lot for the discussion @antfu 🙌
