### ISSUE TITLE
'const' enums are not supported

### ISSUE THREAD

**Issue by robozevel** [antfu/vueuse#142]
Hi 👋

I wish to contribute but unable to run `yarn dev` due to a syntax error in [useWebWorkerFn](https://github.com/antfu/vueuse/blob/master/packages/core/useWebWorkerFn/index.ts#L7):
> `'const' enums are not supported`

what am I missing? 🤔
Thanks!

Node v12.11.1
Yarn 1.22.10
MacOS 10.15.5

**Comment by antfu** [comment]
Good catch up! Just looked into it and surprised found out that babel does not support const enum! 😅

Followed this guide and the problem gets fixed. https://github.com/babel/babel/issues/8741#issuecomment-509041135
