### ISSUE TITLE
"useEventSource" cannot actually close the connection

### ISSUE THREAD

**Issue by chnejohnson** [antfu/vueuse#145]
In my usecase,

```
 setup() {
    const amount = ref<number>(0);

    const { data, close, status } = useEventSource(
      "http://localhost:2222/cash"
    );

    watch(data, (data, _) => {
      amount.value = Number(data);
    });

    return { amount: computed(() => amount.value), close, status };
  }
```
I started the connection on setup and click to close the EventSource, but there is still "pending" on devtool even if the status turn into CLOSED.

![Screenshot from 2020-10-14 14-44-31](https://user-images.githubusercontent.com/31992185/95953386-51e14600-0e2c-11eb-89b0-64fe76da771c.png)

In my own useEventSource code below, the connection can be closed correctly with status "canceled" on devtool.

![Screenshot from 2020-10-14 14-54-00](https://user-images.githubusercontent.com/31992185/95954025-4b070300-0e2d-11eb-95c5-6e227dbba95f.png)

```
export function useEventSource(url: string) {
  const state = ref<string>("");

  const source = new EventSource(url);

  source.onopen = e => {
    console.log("event source opened");
  };

  source.onmessage = function (e) {
    state.value = e.data;
  };

  source.onerror = function () {
    console.log("EventSource failed.");
    source.close();
  };

  const close = () => {
    source.close();
  };

  return {
    state: computed(() => state.value),
    close
  };
}
```
In my nodejs backend, the difference between useEventSource in the project and my useEventSource code is that my case can correctly print "client close the connection".
```
app.get("/cash", function (req, res) {
  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive"
  });
  res.connection.setTimeout(0);

  console.log("start casting coins");

  req.on("close", () => {
    console.log("client close the connection");
  });
});
```

I read the source code but I still don't know how to fix it and what's the difference they are.

**Comment by antfu** [comment]
I am not very familiar with EventSource API. Can you have a look at the discussions in https://github.com/antfu/vueuse/pull/112?

/cc @CharlesOkwuagwu would you mind having a look at this, to see if the behavior is correct and if there is anything we can do to fix it? Thanks!

**Comment by CharlesOkwuagwu** [comment]
@chnejohnson Hi, see the lines below:

https://github.com/antfu/vueuse/blob/86339852f8caacadec2464415b0b05a83b126c2d/packages/core/useEventSource/index.ts#L33-L35

We could explicitly call close after `line 34`.

In your use case, how do you differentiate from `CLOSE `due to network errors? `EventSource `would emit an error, but would typically try to re-connect on its own.

**Comment by chnejohnson** [comment]
@CharlesOkwuagwu Hey, thanks for your response.
I think that there is no error emitted.
And I found the problem is that the "es.close" rewrite the close function of native EventSource API.
[https://developer.mozilla.org/en-US/docs/Web/API/EventSource/close](url)

So that when I invoke close function, it just set the status into 'CLOSED' but the http network is still connected and open, and the backend can still send data to the client.

**Comment by CharlesOkwuagwu** [comment]
@chnejohnson exactly. So I think we should explicitly close the network. We should call our own `close `method after that `line 34 `as I had pointed out, that would explicitly close the connection.

**Comment by chnejohnson** [comment]
@CharlesOkwuagwu 
I'm not sure whether following code can work. I will test it tomorrow.
I guess it can quickly fix this problem, but maybe it's not a good writing style.

``` 
es.close = () => {
   status.value = 'CLOSED';
   es.close()
 }
```

**Comment by CharlesOkwuagwu** [comment]
> @CharlesOkwuagwu
> I'm not sure whether following code can work. I will test it tomorrow.
> I guess it can quickly fix this problem, but maybe it's not a good writing style.
> 
> ```
> es.close = () => {
>    status.value = 'CLOSED';
>    es.close()
>  }
> ```

es.close = () => {
   status.value = 'CLOSED';
   close() // this one, not es.close()
 }

**Comment by chnejohnson** [comment]
@CharlesOkwuagwu 
No, all of three solution above would lead to infinite recursion.
And I found just comment out the code. It works!

```
//  es.close = () => { 
//    status.value = 'CLOSED' 
//  } 
```
Maybe it should need more testing.

**Comment by antfu** [comment]
Should `es.close` be `es.onclose`?

**Comment by chnejohnson** [comment]
hey @antfu 
I don't think so. In your code, the vscode will popup "Property 'onclose' does not exist on type 'EventSource'. Did you mean 'close'?"
I think we just remove the "es.close" in order to prevent EventSource API function "close" from rewriting it. 
So that the "close" function declared outside tryOnMounted, can really do its job, using EventSource.close to disconnect and also setting status value into "CLOSED".

https://github.com/antfu/vueuse/blob/86339852f8caacadec2464415b0b05a83b126c2d/packages/core/useEventSource/index.ts#L15-L21
