### ISSUE TITLE
feat: add useCookies with reactive methods

### ISSUE THREAD

**Issue by crutch12** [antfu/vueuse#148]
Just like https://github.com/reactivestack/cookies/tree/master/packages/react-cookie but in Vue style

I already wrote a composition-api wrapper for [universal-cookie module](https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie) in my work project and want to add pull request to vueuse with this wrapper

But it would require `universal-cookie ` as peerDependency

@antfu what do you think about third party library?

**Comment by antfu** [comment]
While I stil what to keep the main library dependencies free, but I do understand something it's better to introduce some dependencies that can handle the jobs better. So I guess we can have another package, maybe `@vueuse/libs` or `@vueuse/integrations` to put popular packages wrapper that users can opt-in. What do you think? If it's good, I can make the setup so you can better contribute. Thanks!

**Comment by crutch12** [comment]
@antfu 
I think this naming won't be intuitive for other developers, who, for example look for in google: "vue composition-api cookies".
I think it should be separated package like a `@vueuse/cookie` or `@vueuse/universal-cookie`

But I checked `@vueuse/firebase` and `@vueuse/rxjs` and there are no package.json file (where we could add peerDependencies) and it confuses me

**Comment by crutch12** [comment]
Is it okay if I will provide PR for `@vueuse/cookie`?

**Comment by antfu** [comment]
Well, it's probably okay. But my main concern is that cookie is kinda a small utility, making it a separate package meaning we are likely to have a lot of @vueuse/xxx for just simple wrappers. My idea of `@vueuse/integrations` is like a collection of libraries wrappers (with optional deps and tree-shaking) and add some guide to install corresponding libraries (`universal-cookie` in this case) if they would need some of the wrappers. Or think it of `@vueuse/core` but with deps version.

**Comment by crutch12** [comment]
Ok, let's try `@vueuse/integrations`, could you setup it?

**Comment by antfu** [comment]
Sure

**Comment by antfu** [comment]
Done. And I think I should switch to monorepo instead of this magic things, I will do that later :p

**Comment by crutch12** [comment]
solved by https://github.com/antfu/vueuse/pull/150
