### ISSUE TITLE
tryOnMounted/tryOnUnmounted. What does it do?

### ISSUE THREAD

**Issue by lizy0329** [antfu/vueuse#156]
I don't understand what is `Call tryOnMounted() if it’s inside a component lifecycle, if not, do nothing`

**Comment by antfu** [comment]
It should be `Call onMounted() if it’s inside a component lifecycle, if not, do nothing`.

When outside of `setup()`, `onMounted` or `onUnmounted` are not available. This is useful for hooks to be used globally.
