### ISSUE TITLE
TypeScript error with --isolatedModules flag

### ISSUE THREAD

**Issue by neelance** [antfu/vueuse#172]
The [TypeScript compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html) `--isolatedModules` reports an error:
```
node_modules/@vueuse/core/dist/index.d.ts:492:278 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```
It would be nice if vueuse would not prevent the use of this compiler option.

**Comment by antfu** [comment]
I didn't aware of this flag. What can we do to make this supported?
