### ISSUE TITLE
API review, useRefHistory flush default

### ISSUE THREAD

**Issue by matias-capeletto** [antfu/vueuse#181]
Hello! 
Awesome to see the preparation for the first stable release https://github.com/antfu/vueuse/issues/166 🎉 

We have been using useRefHistory for https://github.com/Leniolabs/layoutit-grid using the extended API and it has been working well. The only thing that I am still not sure of is the right API choice to freeze is the default flush:sync. I think we should still try to make it work with the same default, 'pre', as watch/watchEffect.

I had to import batch in several places to fix issues with the flush:sync. I could have placed them in the actions, but it is still easy to get spurious history points. There also seems to be an issue with array refs and splice. Looks like calling splice is generating two history points (maybe a bug in Vue.js itself?).

I have an idea to use two watchers that may enable us to offer pre/post (and also sync as an option), so we could choose pre as the default. I still have to see if it works, but if not, I still think we should try to find a solution. 

@antfu should I create a PR against the new dev branch if I managed to get it right? What do you think?

**Comment by antfu** [comment]
> should I create a PR against the new dev branch if I managed to get it right? What do you think?

Sure! Let's see the PR! I would need to do more experiments about it as well :P

In addition, maybe we can have a `manual` option, and users would need to call `commit()` to create history points explicitly.
