### ISSUE TITLE
Review: Add JSDocs to functions

### ISSUE THREAD

**Issue by antfu** [antfu/vueuse#183]
Add basic JSDocs to each function. The minimal work will be copying the first sentence of docs to it.

## Checklist 

This is a checklist of all the functions of VueUse. It's is useful for review or making changes the go through every function.

### shared (21)
  - [ ] biSyncRef
  - [ ] controlledComputed
  - [ ] debouncedWatch
  - [ ] extendRef
  - [ ] makeDestructurable
  - [ ] pausableWatch
  - [ ] syncRef
  - [ ] throttledWatch
  - [ ] tryOnMounted
  - [ ] tryOnUnmounted
  - [ ] useDebounce
  - [ ] useDebounceFn
  - [ ] useInterval
  - [ ] useIntervalFn
  - [ ] useThrottle
  - [ ] useThrottleFn
  - [ ] useTimeout
  - [ ] useTimeoutFn
  - [ ] utils
  - [ ] watchWithFilter
  - [ ] when

### core (51)
  - [x] asyncComputed
  - [x] createGlobalState
  - [x] onStartTyping
  - [x] useAsyncState
  - [x] useBattery
  - [x] useBrowserLocation
  - [x] useClipboard
  - [x] useCounter
  - [x] useCssVar
  - [x] useDeviceLight
  - [x] useDeviceMotion
  - [x] useDeviceOrientation
  - [x] useDevicePixelRatio
  - [x] useDocumentVisibility
  - [ ] useElementVisibility
  - [ ] useEventListener
  - [ ] useEventSource
  - [ ] useFavicon
  - [ ] useFullscreen
  - [ ] useGeolocation
  - [ ] useIdle
  - [ ] useIntersectionObserver
  - [ ] useLocalStorage
  - [ ] useMediaQuery
  - [ ] useMouse
  - [ ] useMouseInElement
  - [ ] useMutationObserver
  - [ ] useNetwork
  - [ ] useOnline
  - [ ] usePageLeave
  - [ ] useParallax
  - [ ] usePermission
  - [ ] usePreferredColorScheme
  - [ ] usePreferredDark
  - [ ] usePreferredLanguages
  - [ ] useRafFn
  - [ ] useRefHistory
  - [ ] useResizeObserver
  - [ ] useSessionStorage
  - [ ] useShare
  - [ ] useSpeechRecognition
  - [ ] useStorage
  - [ ] useTimestamp
  - [ ] useTitle
  - [ ] useTransition
  - [ ] useVModel
  - [ ] useWebSocket
  - [ ] useWebWorker
  - [ ] useWebWorkerFn
  - [ ] useWindowScroll
  - [ ] useWindowSize

### router (2)
  - [ ] useRouteHash
  - [ ] useRouteQuery

### integrations (3)
  - [ ] useAxios
  - [ ] useCookies
  - [ ] useQRCode

### rxjs (4)
  - [ ] from
  - [ ] toObserver
  - [ ] useObservable
  - [ ] useSubscription

### firebase (2)
  - [ ] useFirestore
  - [ ] useRTDB

**Comment by iBobik** [comment]
Why not to move all docs to JSdoc and generate website from it?
