### ISSUE TITLE
Review: Make global dependencies configurable

### ISSUE THREAD

**Issue by antfu** [antfu/vueuse#184]
Global dependencies such as `window`, `document`, `navigator` should be configurable. #173

## Checklist 

This is a checklist of all the functions of VueUse. It's is useful for review or making changes the go through every function.

### shared (21)
  - [ ] biSyncRef
  - [ ] controlledComputed
  - [ ] debouncedWatch
  - [ ] extendRef
  - [ ] makeDestructurable
  - [ ] pausableWatch
  - [ ] syncRef
  - [ ] throttledWatch
  - [ ] tryOnMounted
  - [ ] tryOnUnmounted
  - [ ] useDebounce
  - [ ] useDebounceFn
  - [ ] useInterval
  - [ ] useIntervalFn
  - [ ] useThrottle
  - [ ] useThrottleFn
  - [ ] useTimeout
  - [ ] useTimeoutFn
  - [ ] utils
  - [ ] watchWithFilter
  - [ ] when

### core (51)
  - [x] asyncComputed
  - [x] createGlobalState
  - [x] onStartTyping
  - [x] useAsyncState
  - [x] useBattery
  - [x] useBrowserLocation
  - [x] useClipboard
  - [x] useCounter
  - [x] useCssVar
  - [x] useDeviceLight
  - [x] useDeviceMotion
  - [x] useDeviceOrientation
  - [x] useDevicePixelRatio
  - [x] useDocumentVisibility
  - [x] useElementVisibility
  - [ ] useEventListener
  - [ ] useEventSource
  - [x] useFavicon
  - [x] useFullscreen
  - [ ] useGeolocation
  - [ ] useIdle
  - [ ] useIntersectionObserver
  - [ ] useLocalStorage
  - [ ] useMediaQuery
  - [ ] useMouse
  - [ ] useMouseInElement
  - [ ] useMutationObserver
  - [ ] useNetwork
  - [ ] useOnline
  - [ ] usePageLeave
  - [ ] useParallax
  - [ ] usePermission
  - [ ] usePreferredColorScheme
  - [ ] usePreferredDark
  - [ ] usePreferredLanguages
  - [ ] useRafFn
  - [ ] useRefHistory
  - [ ] useResizeObserver
  - [ ] useSessionStorage
  - [ ] useShare
  - [ ] useSpeechRecognition
  - [ ] useStorage
  - [ ] useTimestamp
  - [ ] useTitle
  - [ ] useTransition
  - [ ] useVModel
  - [ ] useWebSocket
  - [ ] useWebWorker
  - [ ] useWebWorkerFn
  - [ ] useWindowScroll
  - [ ] useWindowSize

### router (2)
  - [ ] useRouteHash
  - [ ] useRouteQuery

### integrations (3)
  - [ ] useAxios
  - [ ] useCookies
  - [ ] useQRCode

### rxjs (4)
  - [ ] from
  - [ ] toObserver
  - [ ] useObservable
  - [ ] useSubscription

### firebase (2)
  - [ ] useFirestore
  - [ ] useRTDB

**Comment by anteriovieira** [comment]
I @antfu I can do this

**Comment by antfu** [comment]
@anteriovieira that would be great! I think I have done most on dev branch (but kinda randomly), so I made this list. You can help go through the functions and review them a bit. You should have permission to update the list.

Thank you!

**Comment by anteriovieira** [comment]
@antfu , I must send it to dev, right? Considering that we may have changes in the signature of the functions.

**Comment by antfu** [comment]
Yes, let's do that on dev
