### ISSUE TITLE
Extended finite options or composability using filters (was debouncing option for useStorage)

### ISSUE THREAD

**Issue by matias-capeletto** [antfu/vueuse#192]
I was looking into the debouncing option you raised for useStorage and I wanted to first see if the same can be achieved in a more flexible way.

Please take this as a dump of ideas and not a definite API. I thought about this while trying to design the API for other composables, and I want to share it in case it is useful in some way for vueuse.

The problem that I see with adding a denounce option is that we may also want to add a throttle one later (or pausable, or other ideas we may have later). We are adding complexity to the main composable, and users will need to pay for this even if they do not use it. There are other composables like useRefHistory where users may expect the same functionality.

So, what if the API lets the user define the [filtering function](https://www.learnrxjs.io/learn-rxjs/operators/filtering) to be used? I think you called it updater in the useDebounce implementation. I am using `filter` as the option name just because it is called like that in Rx, but I am not married with the name. The signature for filter is ( (fn) => void ) => void

```
const count = useStorage('counter', 0, { filter: debounceFilter(200) })
```

```
const count = useStorage('counter', 0, { filter: throttleFilter(300) })
```

```
const { filter, pause, resume } = pausableFilter() 
const count = useStorage('counter', 0, { filter })
```

`debounceFilter` could be implemented as:
```
export function debounceFilter(delay = 200) {
  return (fn) => useDebounceFn(() => fn(), delay)
}
```

The idea is that inside useStorage, instead of a direct `watch(data, commit, options)` we use `watch(data, filter(commit), options)`
So, the `filter` option gives users the possibility to decide which triggered values to accept from the watch.
Also, if we have these filters in the lib, we can also implement useDebounceRef, useThrotleRef, etc using a more general useFilteredRef

```
export function pausableFilter() {
  const tracking = ref(true)
  function pause() {
    tracking.value = false
  } 
  function resume() {
    tracking.value = true
  }
  function filter(fn) {
    return () => {
      if( tracking.value ) {
        fn()
      }
  }
  return { tracking, pause, resume, filter }
}
```

The filters are composable also, allowing users to create pausable throttled storage for example
```
const { filter, pause, resume } = pausableFilter() 
const count = useStorage('counter', 0, { filter: filter(throttleFilter(300)) })
```

And they can actually create their own filters, pausing or delaying according to their app needs (using other app refs, etc)

I also wonder if we could simplify useRefHistory by removing the pausable part out of the main composable, and letting users choose if they want that functionality
```
const data = ref(0)
const { filter, pause, resume } = pausableFilter() 
const { undo, redo } = useRefHistory(data, { filter })
```

It is also good that we are not adding an extra watch for every filter. Another possible API for composables that are watching an input ref is to expect the user to give us a filtered ref, something like:
```
const data = ref(0)
const { pausableRef, pause, resume } = usePausableRef(data)
const { undo, redo } = useRefHistory(pausableRef)
```
This only works with API that are tracking an input ref (so we can not use it in useStorage), but we could offer this possibility also. 

I think there are other possible APIs we could explore. I thought about letting the user give us the `watch` function to be used, but then you may need to use the same options (flush, deep) in several places. 
For common cases, we can also bundle filters for convenience like:
```
const data = ref(0)
const { undo, redo, pause, resume } = usePausableRefHistory(data)
```
implemented as
```
export function usePausableRefHistory(ref, options) {
  const { filter, pause, resume } = pausableFilter() 
  return { ...useRefHistory(data, { filter }), pause, resume }
}
```
So we can still offer the general composable and specialized ones, and users will only pay for what they use. Take the pausable filter extraction as an example to extrapolate to other cases, because the current API allows users to commit using `resume(true)`. There may be a better API to also support external triggers. Or the filter may also receive the value, so you can implement validation filters, remove values if they are negative, etc. Or that maybe another option orthogonal to this one.

What do you think? Is something like a filter option worth exploring so we do not need to implement debounce/throttle/pausable in each composable? 

Disclaimer: I do not know if I can actually do this myself but looks interesting, so at least I wanted to share it 😃

**Comment by antfu** [comment]
I like this idea! It's definitely more flexible and I do feel the same about having debouncing and throttling at the same time. And I like the `pausableFilter` idea!

About the naming, I am not sure about `filter` as they would potentially be confused with array's `filter`, maybe `eventFilter`? WDYT?

About `useRefHistory`, I am not so sure about extracting `pausableFilter` as I think `pause` and `resume` are fundamental features, having `useRefHistory` and `usePausableRefHistory` can be confusing. Maybe we can reuse the logic internally to reduce duplicated code while exposing the `eventFilter` for debouncing or throttling.

**Comment by matias-capeletto** [comment]
Great! And I agree with leaving useRefHistory pause/resume as part of the core. We can still include a filter option there though for debouncing.

About the name, `eventFilter` is definitely better. Another option is `triggerFilter`, using the naming from Vue's reactivity 
https://v3.vuejs.org/guide/reactivity-computed-watchers.html#watcher-debugging
https://v3.vuejs.org/api/refs-api.html#customref

The customRef example from Vue's doc could be implemented like this for example:
```
function useDebouncedRef(value, delay = 200) {
  const triggerFilter = debounceFilter(200)
  return customRef((track, trigger) => {
    return {
      get() {
        track()
        return value
      },
      set: (newValue) => {
        triggerFilter(() => {
          value = newValue
          trigger()
        }
      })
    }
  })
}
```

And now that I review how we would use this, it should not have been `watch(data, filter(commit), options)`, but `watch(data, () => { filter(commit); }, options)`

I think we should find a way to pass the value (and maybe also the prevValue) to the filter or to another option, or at least think about it so that door is not closed later. 

One possibility is to send the value as a second parameter, like:
```
function filter() {
  return (trigger,value) => {
    if( value > 0 ) {
      trigger()
    }
  }
}
```

But we could also think if the filter should receive the trigger function separately, and return a simpler `(value,preValue) => void` like `curstomRef` set does. In that case, we could write it as
```
function useDebouncedRef(value, delay = 200) {
  return customRef((track, trigger) => {
    return {
      get() {
        track()
        return value
      },
      set: debounceFilter(200)( (newValue) => {
        value = newValue
        trigger()
      })
    }
  })
}
```

And the previous positive numbers filter will be:
```
function filter(trigger) {
  return (value) => {
    if( value > 0 ) {
      trigger()
    }
  }
}
```

In the composable, it would be used directly as `watch(data, filter(commit), options)` now.

We could also implement `resume(true)` with it
```
export function pausableFilter() {
  return (trigger) => {
    const tracking = ref(true)
    function pause() {
      tracking.value = false
    } 
    function resume(commit: true) {
      tracking.value = true
      if( commit ) {
        trigger()
      }
    }
    function filter() {
      if( tracking.value ) {
        trigger()
      }
    }
    return { tracking, pause, resume, filter }
  }
}
```

So, the signature of filters will be that of a filter factory, that receives a trigger (like customRef does) and returns a filter 
But I do not know if this is already too complex. You will also need a `pipe` operator to combine filters, but maybe it is the right tradeoff.

**Comment by matias-capeletto** [comment]
Actually, to make this example from my previous comment work we will need that the filter will forward the value to us
```
function useDebouncedRef(value, delay = 200) {
  return customRef((track, trigger) => {
    return {
      get() {
        track()
        return value
      },
      set: debounceFilter(200)( (newValue) => {
        value = newValue
        trigger()
      })
    }
  })
}
```
like 
```
export function debounceFilter(delay = 200) {
  return (trigger) => useDebounceFn((value) => trigger(value), delay)
}
```
This places more complexity on filter authors but it gives users more flexibility, and I think there may be some cases where it is needed so we do not have to access the watched value by reading other refs. And now that I see it, it is also needed if we want to access the prevValue in the trigger/commit function. For the pausable example, we could support trigger being called without parameters

**Comment by antfu** [comment]
I am actually working on the implementation. To me, use the `customRef` and `watch` might be overkill for this feature. My current implementation:

```ts
export type EventFilter = (invoke: () => void) => void

export interface ConfigurableEventFilter {
  eventFilter?: EventFilter
}

export const bypassFilter: EventFilter = (invoke) => {
  return invoke()
}

/**
 * Create an EventFilter that debounce the events
 *
 * @param ms
 */
export function debounceFilter(ms: number) {
  if (ms <= 0)
    return bypassFilter

  let timer: ReturnType<typeof setTimeout> | undefined

  const filter: EventFilter = (invoke) => {
    if (timer)
      clearTimeout(timer)

    timer = setTimeout(invoke, ms)
  }

  return filter
}

/**
 * Create an EventFilter that throttle the events
 *
 * @param ms
 * @param [trailing=true]
 */
export function throttleFilter(ms: number, trailing = true) {
  if (ms <= 0)
    return bypassFilter

  let lastExec = 0
  let timer: ReturnType<typeof setTimeout> | undefined

  const clear = () => {
    if (timer) {
      clearTimeout(timer)
      timer = undefined
    }
  }

  const filter: EventFilter = (invoke) => {
    const elapsed = Date.now() - lastExec

    clear()

    if (elapsed > ms) {
      lastExec = Date.now()
      invoke()
    }
    else if (trailing) {
      timer = setTimeout(() => {
        clear()
        invoke()
      }, ms)
    }
  }

  return filter
}
```

**Comment by antfu** [comment]
Made a draft PR: https://github.com/antfu/vueuse/pull/194

**Comment by antfu** [comment]
I really like this idea!

Now `useDebounceFn` is like:

```ts
export function useDebounceFn<T extends Function>(fn: T, ms = 200): T {
  return createFilterWrapper(
    debounceFilter(ms),
    fn,
  )
}
```

We can also make some utilities like `pausableWatch` via `pausableFilter` etc.

Please have a look at my PR and wondering what you think :P

**Comment by matias-capeletto** [comment]
Awesome! You already did it 😄 🎉 

I think this is great, it will add a lot of flexibility to the library! And not vueuse could offer a complete suite of filters at one point. 

My only caveat is about how to extend this in the future if we want to support value filters. Even if you do not add that feature now, it may be good to think about it. So:
```
export type EventFilter = (invoke: () => void) => void
```
Could be extended like:

1. passing the value to the event, as events from the browser give you this kind of info
```
export type EventFilter = (invoke: () => void,value) => void
```
2. separating this functionality to another option like valueFilter, that maybe is just a simple `(value) => boolean`

But looks like in both cases, this can be added later.

I think it is good to keep it simple for now 👍 
Maybe the eventFilterFactory option is a vueuse v2 feature 😉

**Comment by antfu** [comment]
I am not sure what you mean for `value`, but I think we can pass the `args[]` as the second argument.

```ts
// `any` should be genertics, just for demo here
export type EventFilter = (invoke: () => void, fn: any, thisArg: any, args: any[]) => void
```

and `invoke` is essential a shorthand for

```ts
fn.apply(thisArg, args)
```

What will be `eventFilterFactory`? If a filter need to accept extra arguments, they can just make a function that creates a filter, just like `debounceFilter` already did.

**Comment by matias-capeletto** [comment]
With `value`, I mean the value that watch gives us and triggered the event (and we also have `prevValue` there available)
I wanted to see if we could implement filters like this also
```
function filter() {
  return (invoke,value) => {
    if( value > 0 ) {
      invoke()
    }
  }
}
```
So you can not only discard events because of timing (debounce/throttle) but also that take into account the value from the source, like https://www.learnrxjs.io/learn-rxjs/operators/filtering/filter, https://www.learnrxjs.io/learn-rxjs/operators/filtering/skipwhile, or any other validation.

About the `eventFilterFactory`, I mean the filter factory as described in this comment: https://github.com/antfu/vueuse/issues/192#issuecomment-723788660, the trigger is passed beforehand while constructing the filter and not at each event, so you can call it from the outside:

```
export function pausableFilter() {
  return (trigger) => {
    const tracking = ref(true)
    function pause() {
      tracking.value = false
    } 
    function resume(commit: true) {
      tracking.value = true
      if( commit ) {
        trigger()
      }
    }
    function filter() {
      if( tracking.value ) {
        trigger()
      }
    }
    return { tracking, pause, resume, filter }
  }
}
```

**Comment by antfu** [comment]
I see. I thought is that the filter is not necessarily called by an watch or reactivity data. They could act as normal functions. Values could be accessed in `args[]`. For example:

```ts
const myFilter = (invoke, fn, thisArg, args) => {
  const event = args[0]

  if (event.x % 2 === 0) // only trigger when mouse.x is even
    invoke()
}

const onMousemove = createFilterWrapper(
  myFilter,
  (event: MouseEvent) => {
    // do something
  },
)

useEventListener(window, 'mousemove', onMousemove)
```

Pausable filter could be 

```ts
import { useDeviceMotion } from "./packages/core/useDeviceMotion"

export function pausableFilter() {
  let tracking = ref(true)

  function pause() {
    tracking.value = false
  }
  function resume(commit: true) {
    tracking.value = true
  }

  const eventFilter: EventFilter = (invoke) => {
    if (tracking.value) {
      invoke()
    }
  }
  return { tracking, pause, resume, eventFilter }
}
```

```ts
const { eventFilter, pause, resume } = pausableFilter()

useDeviceMotion({ eventFilter })

pause()
```

Did you miss anything?

**Comment by matias-capeletto** [comment]
Nice! 🙌 

I like a lot what you did with the `invoke` wrapper, so filter authors do not need to do that.

Interesting also that you also included the `thisArg` parameter, like in Array.map. Do you have a use case in mind for it? Maybe the users can just use bind in that case so you do not need it in the API?

Or I wonder if the order should be the other way around,
```
const myFilter = (invoke, fn, thisArg, args) => {
  const event = args[0]

  if (event.x % 2 === 0) // only trigger when mouse.x is even
    invoke()
}
```
with the (args, thisArg, fn) at the end so people that do not use it, do not have to add the param (I think that will be the common case)
```
const myFilter = (invoke, args) => {
  const event = args[0]

  if (event.x % 2 === 0) // only trigger when mouse.x is even
    invoke()
}
```

**Comment by antfu** [comment]
> Interesting also that you also included the thisArg parameter, 

This could be a common practice to make function wrappers. Passing `this` will make the wrapper more equal to the original function. You have no idea of how users use your wrapper. For example

```ts
class MyClass {
  state = 1

  update: debounced(function () {
	this.state += 1
  })

  call() {
    this.update()
  }
}
```

> the order should be the other way around

Yeah I agree with you. But I am kinda in a dilemma. Having `(args, thisArg, fn)` just looks not natural. I was also thinking to make it an object and let users destructure it.

```ts
const myFilter = (invoke, { args }) => {
  const event = args[0]

  if (event.x % 2 === 0) // only trigger when mouse.x is even
    invoke()
}
```

WDYT?

**Comment by matias-capeletto** [comment]
Yeah, I understand that may be use cases when working with classes for example, but at least from what I see lately utility libraries like lodash are choosing to avoid dealing with this at the library level and leave the user use js features like bind or arrow functions. https://lodash.com/docs/4.17.15#debounce, https://lodash.com/docs/4.17.15#dropWhile, etc.
I think you forgot to pass `this` in your example to `debounce`, it is not trivial even if you allow users to give you the `this` argument. If we ask users to use arrow functions, then things works as spected and they are used to do this for event handlers anyways
```
class MyClass {
  state = 1
  update = debounced(() => {
	this.state += 1
  })

  call() {
    this.update()
  }
}
```
I think the API of vueuse would be simpler for the big majority of users if you do not deal with `this` at all.
About passing the `fn`, do you see an use case there? Because if not, the filter can be just the invoke and the args and we can spread them like a normal function, no extra array indirection 
```
const myFilter = (invoke, event) => {
  if (event.x % 2 === 0) // only trigger when mouse.x is even
    invoke()
}
```
Because it is called like filter(invoke,...args)

**Comment by antfu** [comment]
> About passing the fn, do you see a use case there?

I don't know, yet. `invoke` is something that "leave as it is" and I believe in most of the cases, users would only need `invoke` to make their filters. But think about more advanced usages, you may also want to alter the args passed to `fn`. I can't think about the usage yet, but I would prefer not to limit the possibility of doing things.

```ts
cosnt myArgs = args.slice(0, 1)

fn.apply(thisArgs, myArgs)
```

> spread the args

Yeah, I do like it, this does make the code cleaner. However, it also makes you lose the ability to extend the signature to add more arguments in the future.

---

I think I would prefer to keep the object destructuring style as I would treat this API as an advanced one. It's not ideal for me to trade flexibility for "cleanness". Hope I made myself clear :p

**Comment by matias-capeletto** [comment]
Ya, totally, I also thought about that but the clean version was too tempting 😄 

Also, users can also have an utility if they would want the other interface for their filters too
```
toFilter( (invoke,event) =>{
  if( event.x > 0 ) {
    invoke()
  }
}
```
like
```
function toFilter( fn ) {
  return (invoke,{ args }) => fn(invoke,...args)
}
```
So not a big deal 👍 

Really cool to see the filters feature in the lib 🙌 
That was a lot faster than I expected 🎉
