### ISSUE TITLE
useAxios - async chaining?

### ISSUE THREAD

**Issue by tomexx** [antfu/vueuse#193]
Hi there, is there any way how to utilize more `useAxios` hooks and put them in a chain? How to do that? Thank you!

**Comment by antfu** [comment]
Can you show me an example? Thanks

**Comment by tomexx** [comment]
Well I'd like to `await` the response from one `useAxios` hook and use the response as a an argument for the other

**Comment by antfu** [comment]
Maybe you can consider using [https://vueuse.js.org/?path=/story/utilities--useasyncstate](https://vueuse.js.org/?path=/story/utilities--useasyncstate) which will give you more controls to async behaviors.

**Comment by antfu** [comment]
Closing for stale.
