### ISSUE TITLE
useLocalStorage and useSessionStorage have bad TS signatures

### ISSUE THREAD

**Issue by neelance** [antfu/vueuse#197]
The functions useLocalStorage and useSessionStorage offer TS signatures that accept a third argument `storage`. However, it looks to me as if this third argument is never used.

**Comment by antfu** [comment]
That's a good point, it seems there is no way in TypeScript to "transform" the function signatures with overrides. I was too lazy to clone the overloads from "useStorage" and make it better, so I just reassigned the types.

This might be a good change for us to improve it, along with #198, would you mind to open a PR? Thanks!
