### ISSUE TITLE
bundle not ES5 compatible, breaking IE11

### ISSUE THREAD

**Issue by neelance** [antfu/vueuse#202]
Yes, we still do support IE11. We hope to be able to drop it soon, but today we still do. We have quite some dependencies and all of them seem to ship ES5 compatible bundles except vueuse. Is this intentional?

**Comment by antfu** [comment]
Do you use CDN? Or which bundler are you using?

Polyfills and syntax transforms should be done by the userland bundlers (so as tree-shaking). VueUse is trying to include minimal polyfills possible. But if you are asking for CDN usages, we do need to handle this better.

**Comment by neelance** [comment]
We are using Parcel. We provide polyfills, sure, but with regards to syntax transforms vueuse really seems to be the exception. All other dependencies work fine (Vue, Vuetify, Firebase, and a lot of others).

On https://github.com/parcel-bundler/parcel/issues/1655 someone says:
> Part of the issue is that Parcel seems to strictly require you to use npm packages that follow the general convention that bundled/compiled versions of a package are published as ES5 code for maximal compatibility. The downside is that when (for whatever reason) you need to use a package that does not follow this convention, there doesn't seem to be an easy way to make Parcel transpile the module.

**Comment by neelance** [comment]
I've now added the workaround mentioned on parcel-bundler/parcel#1655: I've added `.browserslistrc` files with the content `node 10.11` to `@vueuse/core` and `@vueuse/shared`. This seems to force Parcel to syntax transform the modules' files.

**Comment by antfu** [comment]
Can't actually help without repro and the error of which line of the code.

**Comment by neelance** [comment]
It's all the arrow functions.

**Comment by antfu** [comment]
I don't see it convincing for libs not to use arrow functions in order to support bundling by Parcel. Probably you are missing some configures. Close this for now. If you find any glitch that prevents it from bundling, maybe try to open a PR instead. Many thanks.

**Comment by neelance** [comment]
Like I said, I added the configuration by adding the `.browserslistrc` files to tell Parcel that the bundle uses a newer JS standard.

I also pointed out that all other packages are working just fine without any manual configuration, so your response basically amounts to "I don't care what the current best practice is and you need to special case my module".

Sure, I agree that it is bad that all packages are forced to use the lowest common denominator to be compatible. Still, I think it should not be the package user who needs to make this work. It would be better if the JS ecosystem can make sure that it works out of the box.

fyi: I perceived your response as a bit rude. Maybe this was not intended. I already submitted a few issues to help with improving this project. An effect may be that I am less likely to do so in the future.

**Comment by antfu** [comment]
I do appreciate your contributions (and the community does) and this is all about the issue and nothing personal. BTW, congrats that you find out the soliton for this problem.

I have asked for a reproduction and detailed information, and the response "It's all the arrow functions." is also rude to me and helped nothing. Other libs use them in their dist too, there is no reason that this particular lib can't. You should provide more information or just point out exactly which lines break your app so I may help to investigate. Or if it's trivial, you can go ahead and draft a PR. That would be the best way to asking help and faster to get things fixed.

Meanwhile, please note this is an open-source project which I spend countless hours and many efforts on making and maintaining it, but offered totally FREE for you to use. I am NOT your customer services and I have no responsibility to answer your questions. The contributions are for the community good not only for me. You are free to fork it, modify it, or even make your own version if you do not agree with the way I do things. And I don't care.

Regards.

**Comment by neelance** [comment]
> I have asked for a reproduction and detailed information, and the response "It's all the arrow functions." is also rude to me and helped nothing.

That's exactly the information I have. It is not a specific line, but quite a number of arrow functions that have not been translated to ES5 equivalents. I do not see that it would be helpful to simply list all occurrences of arrow functions. You can easily find them. Reproduction should have also been clear: Try to load the bundle with IE11. I don't know what other information I could give to you.

> Other libs use them in their dist too, there is no reason that this particular lib can't.

On the other hand, apparently no other library that we use does so. To me, this is an (albeit single) data point that looks like there is some best practice. The comment from the issue I cited also mentions a "general convention". Of course you are free to say that you do not want to follow the same convention because you disagree with it.

> Or if it's trivial, you can go ahead and draft a PR. That would be the best way to asking help and faster to get things fixed.

My initial message asked "Is this intentional?" exactly to figure out if you want to follow this convention or not. If you do want to follow the convention, then we could try to figure out how to modify you build system. I don't want to just drop a PR that modifies the build system.

> Meanwhile, please note this is an open-source project which I spend countless hours and many efforts on making and maintaining it, but offered totally FREE for you to use. I am NOT your customer services and I have no responsibility to answer your questions. The contributions are for the community good not only for me. You are free to fork it, modify it, or even make your own version if you do not agree with the way I do things. And I don't care.

The usual story. I have my own open source projects, I know the situation. I just want to help here. Either we both try to get along or we don't have to. I will not fork this project, I would just use local patches. But as you can see, I would rather prefer to get things upstream and help others.

**Comment by antfu** [comment]
> Is this intentional?

YES. I think I have stated my option in my very first comment, **Polyfills and syntax transforms should be done by bundlers**, not libs. It's always better to transpile down then up. And I think we already meet the agreement.

> Reproduction should have also been clear: Try to load the bundle with IE11. I don't know what other information I could give to you.

No, it's not. Screenshots, repo with your parcel configs setup, error logs, anything. And I have nothing but your words. I don't have IE11 and I am not gonna waste hours to find out that something does not relate to this project. If you do open-source as a maintainer, you should know it. 

> adding the .browserslistrc files to tell Parcel

It's a pretty good and legitimism solution, why you call that workaround?

> apparently no other library that we use does so.

Tell me again.

https://github.com/vuejs/vue/blob/b800e8e9ee4fa4be9b3d6130b5ee82d668066870/dist/vue.esm.browser.js#L121-L122

---

I close this as I think there is nothing that needs to be further discussed, they are either been resolved or answered. There is nothing new from our previous discussions in this comment, I am literally repeating the same things. Again, point out if you believe there is something wrong, or I am not going to keep chatting on this thread.

**Comment by neelance** [comment]
All right, I will not bother you any more.

**Comment by neelance** [comment]
Actually I have to bother you once more, sorry about that. I just want to point out that the vue/composition-api project that you seem to maintain is using `"target": "es5"` in its tsconfig.json, while vueuse is using `"target": "es2017"` in its tsconfig.json. This seems to be the reason why we didn't see any issues when adding vue/composition-api. I don't want to say that you should change it and you don't have to answer. I just want to point out that two projects that you maintain seem to use different policies.
