### ISSUE TITLE
Usign useRefHistory and useStorage together

### ISSUE THREAD

**Issue by matias-capeletto** [antfu/vueuse#203]
If I want to add support to save to local storage the app state, so the state will be preserved next time the app is reloaded
```
const state = ref({ ... })
function serializeState(state) { ... }
function parseState(state) { ... }
```
Right now I need to do something like this:
```
const { undo, redo, pause, resume, history } = useRefHistory(state,{
  dump: serializeState, // custom dump, to avoid double serialization 
  parse: parseState
})
const stateStorage = useStorage('app-state')
watch( history, () => { 
  // user needs to know that last history point is in history[0] and not at the end 
  stateStorage.value = history.value[0] // serialized because dump: serializeState
}, { deep: true }) // we need to watch deeply the history array
```
I want to watch the history instead of the current state ref because I am using pause and resume while the user is dragging stuff around (and I only want to generate one history point for the whole interaction). 

I think this is a common case, and there are several details that people could get wrong. We could add a section to the docs to show how to use these two composables together, but maybe we could extend the API of `useRefHistory` to simplify this pattern.

## Adding a last history ref
```
const { undo, redo, pause, resume, last } = useRefHistory(state,{
  dump: serializeState,
  parse: parseState
})
const stateStorage = useLocalStorage('app-state')
watch( last, () => { 
  stateStorage.value = last.value // serialized because dump: serializeState
})
```
This removes the need for `{ deep: true }` and to know that history[0] is the last history point

## New option for useStorage
```
const { undo, redo, pause, resume, last } = useRefHistory(state,{
  dump: serializeState,
  parse: parseState
})
const stateStorage = useLocalStorage('app-state',{ track: last })
```
I do not find a good name for the option, but the idea will be that everytime that the ref changes, stateStorage is actualized. We could also ask users to do this instead:
```
const stateStorage = useLocalStorage('app-state')
syncRef( last, stateStorage, { flush: 'pre' })
```

## New composable
```
const { undo, redo, pause, resume, storage } = useStoredRefHistory(state,{
  dump: serializeState, // custom dump, to avoid double serialization 
  parse: parseState,
  storage: { key: 'app-state', ...otherStorageOptions }
})
```
I think that this use case may so common that it may justify this last option (name could also be useRefHistoryWithStorage)

What do you think? I am missing a better option?

**Comment by antfu** [comment]
> Adding a last history ref

That's a good idea!

> `track` for useStorage

I like this idea, but I am a bit worried about making `useStorage` too complicated. We would need to document and explain what is going on when using `track` and adding logic to handle it. I feel the `syncRef` usage is more explicit and clear for reading the code.

> useStoredRefHistory

Similar to my previous point, I am thinking this could be easily done on the userland. I think this is what "Composable" means.

Maybe we can have a "Best Practices" or "Code Showcases" section in our docs which people can share some of the patterns you used to make composable that fit with their needs (like the usages and reasons you provided in this issue). It can help users to see how to use this lib and the possibility of combining different functions to achieve complex logic. I do have some interesting usages in my 100 day project and I would love to share as well.

WDYT?

**Comment by matias-capeletto** [comment]
Great, I think 'last' will be a good addition, with that the above patterns are already manageable. I'll check if I can draft PR for this soon.

I agree with what you said about the other two options. A "Best Practices" section would be interesting, but I see that as a more general section in the spirit of the "Guide"
But I understand what you mean, maybe two new sections could be added: "Tutorials" where this kind of patterns could be shared in a more blog post like structure (and there could be links from the docs of each composable pointing to them, like a more section at the end of the composable docs). Another interesting section could be "Examples", where you can show mini apps, in the spirit of your 100 day project, that showcase composable patterns with a real app structure.

PS: Totally unrelated to vueuse. Your 100 day project is turning into quite a beautiful showcase. Do you accept feature requests? :D 
I was browsing the site and occurred to me that if you add next/prev buttons, it would read like pages of a book :heart:

**Comment by antfu** [comment]
While "Guide" is aimed to be general docs for the overall libs. "Best Practices" can be a community based "the place to share" and they can be blog posts or some other forms. "Examples" can be good but I guess I don't have much time on this, maybe it can be another community-based thing.

> re: 100 day

Thank you and glad you like it! The code is not ready to be open-source yet (but will be!). And I would like to focus more on the content instead of managing minor changes at this moment. So keep tuned a bit. Thanks for the suggestion and I will implement it later :P
