### ISSUE TITLE
List of issues with current documentation

### ISSUE THREAD

**Issue by sibbng** [antfu/vueuse#217]
While this repo is currenly under heavy development, I though creating an Issue would be better than a PR.

[useIntersectionObserver](https://vueuse.js.org/?path=/story/sensors--useintersectionobserver)
- API has changed but usage example on docs not updated yet.

[useParallax](https://vueuse.js.org/?path=/story/sensors--useparallax)
- Remote source have SSL issues. Chrome forces to load images on https. You can't access that sources unless you manually visiting sources and ignoring ssl warning.
- `tilt` and `roll` says `.nan` and demo not working.

[useAsyncState](https://vueuse.js.org/?path=/story/utilities--useasyncstate)
- Demo not working.

[useTimeoutFn](https://vueuse.js.org/?path=/story/animation--usetimeoutfn), [useTimeout](https://vueuse.js.org/?path=/story/animation--usetimeout), [useAsyncState](https://vueuse.js.org/?path=/story/utilities--useasyncstate)
- Navigating to other pages from this pages says `Maximum call stack size exceeded`

**Comment by sibbng** [comment]
[useAsyncState](https://vueuse.js.org/?path=/story/utilities--useasyncstate)
- Demo not working.

[useGeolocation](https://vueuse.js.org/?path=/story/sensors--usegeolocation)
- Documentation broken.

**Comment by antfu** [comment]
Thanks a lot! Should be fixed.
