### ISSUE TITLE
Run npm run dev, but failed for lack dependencies.

### ISSUE THREAD

**Issue by Alfxjx** [antfu/vueuse#224]
after install the dependcies, I run `npm run dev ` to start the storybook but failed.
from the error stack I noticed that three dependcies cannot be found: 
- universal-cookie (in useCookie)
- qrcode  (in useQRCode)
- @vueuse/shared (in some other dirs)

Should these three packages be added in the `package.json` ?

**Comment by antfu** [comment]
Did you use `yarn` to install the dependencies?

**Comment by Alfxjx** [comment]
I use `npm i` before and it works without any problems when I use `yarn`, Thank you
So is it no need to add such dependencies into the `package.json` ?

**Comment by antfu** [comment]
No. I think the presence of `yarn.lock` is enough to tell this is a yarn project. Also mentioned in the contributing guide docs.

Meanwhile, doing a self recommendation here :P  - [ni](https://github.com/antfu/ni) can detect the projects' preferred node package manager automatically without you worrying about it.

Closing now.
