### ISSUE TITLE
Type check oddity

### ISSUE THREAD

**Issue by Jogai** [antfu/vueuse#231]
Its not high priority, and possibly not even an issue of your code, but I installed rc-3 and get an eslint error:

```
ERROR in c:/some/path/node_modules/@vueuse/core/dist/index.d.ts(351,17):
351:17 Cannot find name 'Coordinates'.
    349 | declare function useGeolocation(options?: GeolocationOptions): {
    350 |     isSupported: boolean | undefined;
  > 351 |     coords: Ref<Coordinates>;
        |                 ^
    352 |     locatedAt: Ref<number | null>;
    353 |     error: Ref<{
    354 |         readonly code: number;
Version: typescript 4.1.2

**Comment by antfu** [comment]
Do you have `"lib": ["DOM"],` in your `tsconfig.json`? Can you share a minimal reproduction? Thanks

**Comment by shinnosuke-ooyama** [comment]
I had the same problem. Since TypeScript 4.1.2, Coordinates has been removed and replaced with [GeolocationCoordinates](https://github.com/microsoft/TypeScript/blob/f1e53da978f728262c5c3e37ffee7890022e7cc2/lib/lib.dom.d.ts#L5668).

**Comment by antfu** [comment]
@shinnosuke-ooyama That was useful, thanks! Just updated the deps and types, it should work on rc.4. (and hope we don't break TS<4.1?)

**Comment by DarkXanteR** [comment]
For TS <4.1:  Cannot find name 'GeolocationCoordinates'.

**Comment by Jogai** [comment]
Tried to make a minimal repro, but it took too long. You fixed it already, thanks!

**Comment by antfu** [comment]
@DarkXanteR If you don't want to bump your TS version, maybe you can set this in tsconfig.json

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```
