### ISSUE TITLE
Use Prettier

### ISSUE THREAD

**Issue by sxzz** [antfu/vueuse#237]
是否可以使用 `prettier` 来统一代码风格，现在提 PR 不太方便 😓

Is it possible to use `prettier` to unify the code style, it is not convenient to send PR now 😓

**Comment by antfu** [comment]
Sorry but NO. I already have ESLint setup for styling. I am personally not a fan of mixing ESLint and Prettier together (using them individually is OK). Thanks for bringing this up.

**Comment by sxzz** [comment]
So how do you format the code. Using the formatting tool of vscode?

**Comment by antfu** [comment]
`eslint --fix`. If you have ESLint plugin installed on VSCode, you can let it automatically fix them for you.

**Comment by sxzz** [comment]
But...When I writing code, it always marks red. It looks very uncomfortable.

**Comment by sxzz** [comment]
So I still tend to use a unified code formatting tool.

**Comment by sxzz** [comment]
Oh thx. It should be good.

**Comment by matias-capeletto** [comment]
@sxzz just in case, `prettier.requireConfig` is false by default. Set it to true to avoid firing prettier for this project.
![image](https://user-images.githubusercontent.com/583075/101158325-d6ca2e00-362b-11eb-9adb-b564eba074cd.png)

**Comment by antfu** [comment]
To me, prettier is an opinionated formatter that does not offer much customization for you and does not respect your existing formats. It's good to be used out of the box. On the other hand, ESLint gives you much more fine-grained control over your styling. They kinda overlapping their features and when ESLint has a well-configured setup, I don't see much value to have them together and do the formatting twice.

You can find more of my opinions on this here: https://twitter.com/antfu7/status/1279149211523538944

> When I writing code, it always marks red.

Well, that's a part I didn't think about much. But I think that you well still have some red lines when you code `let` on a const value for example. Or if you have ESLint + Prettier setup, prettier will also output error on styling.

**Comment by sxzz** [comment]
Thank you very much. I learned a lot. 👍👍

**Comment by sxzz** [comment]
@antfu And we should ignore the `.vscode/settings.json`, then I can disable `prettier`.

**Comment by antfu** [comment]
How would that affect it tho?
