### ISSUE TITLE
feat: useElementVisibility with custom scroll target .

### ISSUE THREAD

**Issue by amrbashir** [antfu/vueuse#251]
I happened to have a use case when the scrolling in my page wasn't on the document object and thus `useElementVisibilty` never changes since underneath it uses `useWindowScroll`, I could submit a PR if that's acceptable. 

for now I am using a custom version of `useElementVisibilty` that uses `useEventListener` to attach a scroll event on my scrolling element.

**Comment by antfu** [comment]
Sure, let's see the PR!
