### ISSUE TITLE
[npm update error]Unsupported platform for fsevents@2.1.3 in wsl2

### ISSUE THREAD

**Issue by lizy0329** [antfu/vueuse#255]
When i try to run `npm update` in wsl2, I get a error: `npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

In my case, the solution is setting optionalDependencies - fsevents in package.json

```
"optionalDependencies": {
  "fsevents": "^2.1.3"
},
```

Should we need to update the package.json for this error?

System Version:
wsl2: Ubuntu 20.04
node: 12.18.2
npm: 6.14.5

**Comment by antfu** [comment]
We don't directly depend on it, you might need to check the other dependencies from your project.
