### ISSUE TITLE
add useGlobalConfig suggestion

### ISSUE THREAD

**Issue by xxholly32** [antfu/vueuse#261]
get vue [Global config](https://v3.vuejs.org/api/application-config.html#globalproperties)

simple code demo:

```
import { getCurrentInstance } from 'vue'
export function useGlobalConfig(key) {
  const vm: any = getCurrentInstance()
  if (key in vm.proxy) {
    return vm.proxy.key
  }
  return {}
}
```

**Comment by antfu** [comment]
I am not sure if it's clear what it's for. Also mentions that global config is the Vue 3 only thing. Exposing keys on `proxy` are not necessary from the global config. I would suggest using it in the userland composable utilities instead of included in VueUse.
