### ISSUE TITLE
Add end hook to useTransition util

### ISSUE THREAD

**Issue by scottbedard** [antfu/vueuse#266]
Hi, sorry to keep bugging you about this utility! I'm using it a lot right now. The issue I'm running into is that there isn't a great way to chain transitions together. We can get close with the following techniques, but each has downsides. The first option is to use a `setTimeout` with matching duration. 

```ts
const source = ref(0)

const transitionedValue = useTransition(source, { duration })

source.value++;

setTimeout(startNextTransition, duration)
```

This works, but doesn't have a smooth hand-off because of race conditions. The second option is to watch the transitioned value.

```ts
const transitionedValue = useTransition(source, { duration })

watch(transitionedValue, value => {
  if (value === source.value) {
    startNextTransition()
  }
})
```

This provides a smooth handoff, but is not efficient. It adds an extra reactivity binding, and fires it on every requestAnimationFrame. I also suspect it would be difficult for transitions where the progress can exceed 0 to 1

I think the simplest solution would be to accept a callback [that is fired here](https://github.com/antfu/vueuse/blob/74e6de910f6f4f07070d24378a9029020820bb0d/packages/core/useTransition/index.ts#L106), when the transition ends. The API for this might look something like this, and would not be a breaking change.

```ts
useTransition(source, { onEnd: startNextTransition })
```

Would you be open to this addition?

**Comment by antfu** [comment]
Sounds good and reasonable! I am thinking about the naming tho, do you think it's better to have `onStarted` `onFinished`?

**Comment by scottbedard** [comment]
@antfu Using `onFinished` works for me! I don't know if we really need a start hook though. Since the user changing the base number is what starts a transition, in a sense they already have that hook.

There is also one other change I might make while I'm in here, and that is doing the same thing I did to `duration` to the `transition` property, and making it a `MaybeRef<EasingFunction | CubicBezierPoints>`. My need for dynamic transitions come from this setup of running the same transition over and over again. It would be nice if I could make the first have an ease-in curve, make all middle ones linear, and the trailing edge ease-out.

**Comment by antfu** [comment]
Since we are having hooks(callbacks), I think it's better to have `onStarted` in pair of `onFinished`. Think you might make a hight order composable that uses this function but you don't have direct access to the base ref (or controlled by another scope), having the `onStarted` hook can help you aware of when it starts.

About the reactive parameters, sure! I'd love to have the parameters reactive as many as possible. I think that's one of the things making Vue composable different for the plain functions. Please go ahead, thanks!
