### ISSUE TITLE
Typings for useVModel

### ISSUE THREAD

**Issue by praburangki** [antfu/vueuse#270]
Let's say I have a prop that has a `string` type and here's an example of the code:

 ```js
const foo = useVModel(props, 'word');
```
 
 Now `foo` has an `unknown` type, and I believe it is caused by this part:
 
 ```js
declare function useVModel<P extends object>(props: P, key: keyof P, emit?: (name: string, value: any) => void): WritableComputedRef<unknown>;
```
 
 So is it possible to get the original prop type to pass it to this composition?

**Comment by praburangki** [comment]
I'm not an expert with Typescript but I hope this helps:

#271

**Comment by antfu** [comment]
Thanks!
