### ISSUE TITLE
useStorage problem

### ISSUE THREAD

**Issue by timarito** [antfu/vueuse#272]
Hello! Sorry for my bad english. I've got one problem with `useStorage` function.
If i write following code:
`const user = useStorage('name', 'Bob');`
`console.log(user.value);`
it will be 'Bob' in my console and localStorage will be empty, because `storage.getItem('name')` will return `null`, not `undefined`. And key `name` with value `Bob` will not be setted in my localStorage initially.

![image](https://user-images.githubusercontent.com/31849021/103445940-13795b80-4ca4-11eb-9614-302bb64f93b4.png)

My browser: Google Chrome 87.0.4280.88

**Comment by antfu** [comment]
Good catch up! Mind open a PR for it? Thanks
