### ISSUE TITLE
extendRef won't work with Vue2 refs

### ISSUE THREAD

**Issue by IlCallo** [antfu/vueuse#280]
Seem like refs created via `@vue/composition-api` [are sealed](https://github.com/vuejs/composition-api/blob/5e5001a2d981605780fa123ae3a5cfe10c275bac/src/reactivity/ref.ts#L91), so `extendRef` will throw as it tries to define a new property on the ref object.

The sealing is on purpose, so I guess it's working (not working, actually) by design and a note should be added to the docs, describing this limitation

**Comment by antfu** [comment]
Thanks!
