### ISSUE TITLE
Compile error with 4.0.6  Module '"../../../vue/types"' has no exported member 'Ref'

### ISSUE THREAD

**Issue by RPainter8West** [antfu/vueuse#291]
Error introduced in 4.0.6
Reverting to 4.0.5 is OK

ERROR in ./node_modules/@vueuse/core/dist/index.d.ts(4,10):                                       4:10 Module '"../../../vue/types"' has no exported member 'Ref'. Did you mean to use 'import Ref from "../../../vue/types"' instead?
    2 | export * from '@vueuse/shared';
    3 | import { Ref, Vue, UnwrapRef, ComputedRef, WritableComputedRef } from 'vue-demi';
  > 4 | import { Ref as Ref$1 } from 'vue';

**Comment by RPainter8West** [comment]
I'm using vue 2.6.12

**Comment by antfu** [comment]
Should be fixed in 4.0.7. Thanks.

**Comment by RPainter8West** [comment]
Thanks for the quick attention. But I just pulled down 4.0.7 and am getting the same error

**Comment by RPainter8West** [comment]
Confirmed good now. Thanks.
