### ISSUE TITLE
useStorage does not allow store 0 (falsey values in general)

### ISSUE THREAD

**Issue by vmihailenco** [antfu/vueuse#46]
In my case `0` is the array index  which it is rather common I think. Instead default value is used - https://github.com/antfu/vueuse/blob/master/packages/core/useStorage/index.ts#L9-L11

**Comment by antfu** [comment]
@vmihailenco Thanks for the feedback, please update the package to `x.0.17`. You can bind primitives now

```ts
const ref1 = useStoragePlain('key1', 0)
const ref2 = useStoragePlain('key2', true)
```

**Comment by vmihailenco** [comment]
Thanks, `useStoragePlain` works, but `useStorage` still does not. If that is intented - I will be using `useStoragePlain` for primitives.

**Comment by vmihailenco** [comment]
I've spoken too early - both seems to be broken now. You can check https://vueuse.js.org/?path=/story/state--usestorageplain which shows `NaN` (and I get the same value in my code). And `useStorage("foo", '')` seems to return `""` now.

**Comment by antfu** [comment]
@vmihailenco Oh, thanks! Fixed in `x.0.18`.

Yes, it's intended. I will see if I can generalize them into one. But for now, please use `useStorage` for objects and `useStoragePlain` for primitives. Thanks.

**Comment by antfu** [comment]
Hi @vmihailenco, I just release a new version x.0.19.

`useStorage` now supports objects and primitives, along with `useLocalStorage` and `useSessionStorage`. `useStoragePlain` is no longer needed :)

**Comment by vmihailenco** [comment]
Thanks @antfu - I will make sure to try it once new version is available at npm. I just tried and 2.0.18 is still the latest version available.

**Comment by antfu** [comment]
Somehow the recent @rollup/plugin-typescript update made the building failed silently. I have made a rollback and release x.0.20. Please check it out, it should work fine this time.

**Comment by vmihailenco** [comment]
Seems to work fine - thank you!
