### ISSUE TITLE
Adding utility to test viewport visibility

### ISSUE THREAD

**Issue by scottbedard** [antfu/vueuse#60]
First off, awesome repo you have here!

Would you accept a utility for determining a component's position within the viewport? This sort of thing can be handy when trying to defer expensive operations like data fetching or complex rendering. Here is a brief example of what I am proposing...

```vue
<template>
  <div>
    {{ elementIsVisible ? "I'm visible in the viewport" : "You can't see me" }}
  </div>
</template>

<script>
export default {
  setup() {
    const { elementIsVisible } = useElementVisibility();

    return { elementIsVisible };
  },
};
</script>
```

If you're open to this util, I'll put together a PR. And just for fun, here is a more realistic example showing how this kind of thing could be used to do infinite-scroll pagination 🤷‍♂️

```js
import { useElementVisibility } from '@vueuse/core'

export default {
  setup() {
    const { elementIsVisible } = useElementVisibility();

    return { elementIsVisible };
  },
  watch: {
    elementIsVisible(visible) {
      if (visible) this.$emit('enter-viewport');
    },
  },
};
```

```vue
<template>
  <div>
    <Whatever
      v-for="thing in things"
      :thing="thing"
      :key="thing.id"
    />
    <InfiniteScroll @enter-viewport="fetchMoreArticles" />
  </div>
</template>
```

**Comment by scottbedard** [comment]
Quick update, I was bored so I threw together a basic implementation. Let me know if there is anything you want to tweak. One thing that might be nice to add is a "threshold", so we can treat something as on-screen once it gets within 200px or whatever.

Also if you decide you don't want this util, just go ahead and close the issue/pr 👍

**Comment by antfu** [comment]
It looks great, thank you for the proposal and implementation! I have left some comments in the PR, please have a look :)

For the threshold, I am not sure what use cases this utility would be. A basic one comes in my mind would be returning an `invisible | partial | visible` state. Another way with better controllability (but more complex and costly) might be returning an object with `visibleArea` `visbileWidth` `visibleHeight` `visableState` etc.

What do you think?

**Comment by scottbedard** [comment]
My use case for a threshold is [this page](https://speedcube.site/records). I'd like to avoid rendering 3D content that is off the screen, but it might be nice to render it when it is soon to be on screen to avoid a flicker. This could be over-optimizing though, so why don't we keep it simple to start and return a boolean. If it turns out this is not enough, it'll be an easy option to add and won't be a breaking change.

I'll go ahead and make the changes you suggested in the PR, I like that better. I'm not sure what a use case is for knowing when something is partially in the viewport though 🤔

**Comment by antfu** [comment]
Sure, let's keep it simple first.

Awesome website btw :)
