### ISSUE TITLE
Feature Request: New Hook useWorkerFunction

### ISSUE THREAD

**Issue by Donskelle** [antfu/vueuse#69]
Hey, i would like to contribute a port of https://github.com/alewin/useworker.
Its a Hook to extract heavy operation right in your Component Code without writing extra files. It uses [Object Url](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to create workers at runtime and represent workers as promises.
I really like it and i would like to use it in Vue. What do you think of it?

I've done some work already, but would like to get some Feedback first.

First thing i am struggleing with is babel. It converts the code i am extracting to the worker, which is fine but then uses babel helper functions in the extracted code, wich aren't available in the worker context. How can i solve that issue? Is there a way to tell babel, this is worker code dont use helpers? Or is this a thing the limits the ability of that hook?
Somehow i haven't had any issues with that in react

**Comment by antfu** [comment]
It looks very cool on first glance. PR is welcome :)

I am not very familiar with web worker thing, but I would love to learn. Maybe let's see the PR first and then I may able to do some help. Looking forward to that, Thanks!👍

For the naming, I would prefer useWebWorkerFn or useWebWorkerFunction to better align with the existing useWebWorker one.

**Comment by Donskelle** [comment]
I've opened a pr.
