### ISSUE TITLE
`StopHandle` has been renamed to `WatchStopHandle`

### ISSUE THREAD

**Issue by danielroe** [antfu/vueuse#77]
In the [latest beta](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#300-beta5-2020-04-30), `StopHandle` has been renamed to `WatchStopHandle` which means that `@vueuse` currently causes a type error.

**Comment by antfu** [comment]
Currently `@vue/composition-api` is misaligned with the latest beta, I am still wait for several PRs getting merge so that I can move on to the latest apis. Thanks for the info and please keep tuned!

**Comment by antfu** [comment]
`@vue/composition-api` seems to be not actively maintained for some reason. I decided not to wait for it and make polyfill on my own. 

Can you show me how do you get the type error? I didn't see which function is using it.

**Comment by danielroe** [comment]
@antfu Having just checked, this is no longer a problem in the latest versions of `vueuse` and `vue`.
