### ISSUE TITLE
useStorage("anyKey", true) defaults to false

### ISSUE THREAD

**Issue by jonjanisch** [antfu/vueuse#78]
Version: 2.0.26 (Vue 2)
Chrome: 81.0.4044.12 on OSX

```
const myBool = useStorage("anything", true);

watchEffect(() => {
  console.log(myBool.value); // prints false
});
```
I put a breakpoint in useStorage and in the read method, there seems to be a bug:

```
// rawValue is set to null if key is not in local storage
var rawValue = storage.getItem(key);

// check specifically looks for undefined but rawValue is null
if (rawValue === undefined && defaultValue) {
```

Due to the null/undefined mixup, the code enters the else clause and there seems to be an issue there too.

`data.value = Serializers[type].read(rawValue, defaultValue);`

If passes in two values to the serializer (rawValue=null, defaultValue=true), but the serializer's read method only takes one argument:

```
boolean: {
        read: function (v) { return v === 'true'; },
        write: function (v) { return String(v); },
    },
```
Since the first argument is null, it returns false.

**Comment by antfu** [comment]
Thanks for helping investigate! Fixed in 0.0.27
