### ISSUE TITLE
Feature: eventBus

### ISSUE THREAD

**Issue by Leecason** [antfu/vueuse#91]
Hi! In Vue3, vue instance no longer implement the event emitter interface.

So `eventBus` will no longer be available.

```js
import Vue from 'vue';
const bus = new Vue();

bus.$on('xxx', '...');
bus.$emit('xxx', '...');
```

there's a way to implement this event emitter/pubsub feature by composition-api?

**Comment by antfu** [comment]
Hi @Leecason. From the case you provide, it's more like a general bus/boardcast. I don't see it's related to Vue much. Can you show me more examples of your usage? Thanks

**Comment by antfu** [comment]
And if you need a bus, maybe you can try [mitt](https://github.com/developit/mitt) :)

**Comment by Leecason** [comment]
Thanks for the reply.
I have known about `mitt`, but this package has no dependencies, so I think it is possible to integrate eventBus (like `mitt`) into a hook or some other advice?

usage code: 

```js
// A.vue
setup () {
  const { emit } = useBus();

  const onClick = () => {
    emit('click A');
  };

  return { onClick };
}
```

```js
// B.vue
setup () {
  const { on } = useBus();

  onMounted(() => {
    on('click A', () => // do something);
  });
};
```

**Comment by antfu** [comment]
```ts
import mitt from 'mitt'

const createBus = () => {
  const emitter = mitt()
  
  return () => {
    on(key: string, fn: function) {
      emitter.on(key, fn)
    },
    emit(key: string, obj: any) {
      emitter.emit(key, obj)
    }
  }
}

const useBus = createBus()
```

Something like this?

**Comment by Leecason** [comment]
Yes, awesome, will this hook be integrated into this package?

**Comment by antfu** [comment]
I still recommend using mitt, as I can't do any better than it. If you do want to ask for this feature, the best solution I can have is to make a plugin `@vueuse/mitt` that would still require you to install `mitt`.

**Comment by Leecason** [comment]
Thank you, I'll just do it on my own project.
